/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-28 07:03:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.Admin;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1687935668304L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1687914375762L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.Admin");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	session.invalidate();
	String adminId = ""; //adminIdを格納する変数
	String password = ""; //passwordを格納する変数
	String error = (String) request.getAttribute("error");
	String cmd = (String) request.getAttribute("cmd");

	if (cmd == null) {
		cmd = "";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>ログイン画面</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("button.otoiawase-button {\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tgrid-gap: 8px;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tbackground: 0 0;\r\n");
      out.write("\tborder: 1px solid #000;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tflex-shrink: 0;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tgap: 8px;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\tline-height: 1.5;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("\ttransition: all .14s ease-out;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.otoiawase-button:hover {\r\n");
      out.write("\tbox-shadow: 4px 4px 0 #000;\r\n");
      out.write("\ttransform: translate(-4px, -4px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.otoiawase-button:focus-visible {\r\n");
      out.write("\toutline-offset: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.loginbutton {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tappearance: none;\r\n");
      out.write("\tpadding: 0px 12px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-color: rgb(249, 251, 250);\r\n");
      out.write("\tborder: 1px solid rgb(137, 151, 155);\r\n");
      out.write("\tbox-shadow: rgb(6 22 33/ 30%) 0px 1px 2px;\r\n");
      out.write("\tcolor: rgb(61, 79, 88);\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\theight: 36px;\r\n");
      out.write("\ttransition: all 150ms ease-in-out 0s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.loginbutton:hover {\r\n");
      out.write("\tcolor: rgb(61, 79, 88);\r\n");
      out.write("\tbackground-color: rgb(255, 255, 255);\r\n");
      out.write("\tborder: 1px solid rgb(93, 108, 116);\r\n");
      out.write("\tbox-shadow: rgb(0 0 0/ 30%) 0px 4px 4px, rgb(231, 238, 236) 0px 0px 0px\r\n");
      out.write("\t\t3px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ヘッダー部分 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("\tfont-family: 游ゴシック, 游ゴシック体;\r\n");
      out.write("\tbackground-color: rgba(70, 155, 240, 0.1);\r\n");
      out.write("\tmargin-bottom: 50px;\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.top {\r\n");
      out.write("\tfont-family: 游ゴシック, 游ゴシック体;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\theight: 34px;\r\n");
      out.write("\tpadding: 0 13px;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("\ttransition: all .3s ease;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder-color: #e8e8e8;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tline-height: 16px;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.top:hover {\r\n");
      out.write("\tbackground: #e8e8e8;\r\n");
      out.write("\tcolor: #3d3d3d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo span.remark {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo:hover span.remark {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tline-height: 1.2em;\r\n");
      out.write("\tmargin: 0.5em;\r\n");
      out.write("\tpadding: 0.5em;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("\tleft: 80px;\r\n");
      out.write("\twidth: 12em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

	String[] msg = new String[7];

	// 設定開始（メッセージの内容を設定してください）

	msg[0] = "今、この瞬間を幸せでいましょう";
	msg[1] = "あなたの欠点を愛してくれる人が本当の友達です";
	msg[2] = "何事も感謝の気持ちが大切です";
	msg[3] = "辛い時こそ心から笑おう";
	msg[4] = "みんなの思いやりがぶつかり合っただけ";
	msg[5] = "逆境が人に与えるものこそ美しい";
	msg[6] = "夢を見るのに、遅すぎるということは無い";

	// 設定終了

	int no = (int) (Math.floor(Math.random() * msg.length));

	String message = msg[no];

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<table style=\"margin: auto; width: 100%;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"left\" style=\"width: 25%\"><div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<img style=\"margin-left: 20px;\" height=\"70px\" align=\"top\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"Ose-tLOGO.png\" alt=\"Ose-t\"><span class=\"remark\">＜");
      out.print(message);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td align=\"center\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 50%; text-align: center; font-size: 30px; font-weight: bold;\">神田英会話スクール\r\n");
      out.write("\t\t\t\t\t<div style=\"font-size: 20px; font-weight: normal;\">お問い合わせ</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td align=\"right\" style=\"width: 25%;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/view/menu.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"send-button\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"top\" style=\"margin-right: 20px\">トップ</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table style=\"margin-left: 250px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"2\"><img width=\"450px\" height=\"450px\"\r\n");
      out.write("\t\t\t\tstyle=\"object-fit: cover\" src=\"top.png\" alt=\"Sorry No Image\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tstyle=\"text-align: left; font-size: 50px; margin-bottom: 0px; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t<strong> さあ、<br>英会話を始めよう。\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</p> <br>\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tstyle=\"text-align: left; font-size: 30px; margin-top: 0px; margin-bottom: 0px; margin-left: 10px;\">無料相談受付中</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: right; margin-right: 300px\">\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/view/inquiryForm.jsp\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-left: 10px\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" style=\"margin-right: 20px\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"otoiawase-button\">お問い合わせはこちら</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 管理者ログイン -->\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/login\" method=\"post\">\r\n");
      out.write("\t\t\t<table style=\"margin: auto; border: 0; width: 100%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t<hr\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: right; height: 1px; background-color: gray;\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; width: 120px\">\r\n");
      out.write("\t\t\t\t\t\t<p>管理者の方はログイン</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t<hr style=\"text-align: left; height: 1px; background-color: gray;\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table style=\"margin: auto; border: 0\"F>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- エラーメッセージ表示 -->\r\n");
      out.write("\t\t\t\t\t");

						if (cmd.equals("login")) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align: center; color: red\">※ログインIDもしくはパスワードが違います※</h3>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: left\"><font color=\"#444\">ログインID</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=text size=\"60\" name=\"adminId\"\r\n");
      out.write("\t\t\t\t\t\tvalue=");
      out.print(adminId);
      out.write("></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: left\"><font color=\"#444\">パスワード</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=password size=\"60\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\tvalue=");
      out.print(password);
      out.write("></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" name=\"login\" class=\"loginbutton\">ログイン</button>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- フッター部分 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("\tfont-family: 游ゴシック, 游ゴシック体;\r\n");
      out.write("\tbackground: rgba(70, 155, 240, 0.2);\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ボタン全体 */\r\n");
      out.write("#page_top {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 10px 0;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("\ttransition: all .3s ease;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder-color: #e8e8e8;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tline-height: 16px;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tpadding-bottom: 5px;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Font Awesome */\r\n");
      out.write("#page_top::before {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page_top:hover {\r\n");
      out.write("\tbackground: #e8e8e8;\r\n");
      out.write("\tcolor: #3d3d3d;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\" style=\"text-align: center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" id=\"page_top\">ページトップ</a> <br>© 2023\r\n");
      out.write("\t\t\tKandaEnglishSchool. All Right Reserved.\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
